python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/PhaseI/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeAsymptotic --makeAsymptotic --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh   --runCombinationOnly --runWWWZCombination --fakeType fakeLepton

python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/PhaseI/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeProfileLikelihood --makeProfileLikelihood --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh --noGenerateCards --runCombinationOnly --runWWWZCombination  --fakeType fakeLepton

python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/PhaseII/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeAsymptotic --makeAsymptotic --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh  --runCombinationOnly --runWWWZCombination  --fakeType fakeLepton

python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/PhaseII/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeProfileLikelihood --makeProfileLikelihood --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh --noGenerateCards --runCombinationOnly --runWWWZCombination  --fakeType fakeLepton

python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/Aged/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeAsymptotic --makeAsymptotic --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh  --runCombinationOnly --runWWWZCombination  --fakeType fakeLepton

python python/runFakeRateExtrapolation.py --datacardDIR output/DataCards_Combination_WW_WZ_v3/Aged/Polarized/fakeRateExtrapolation/ --inputVariable DeltaPhi_JJ_ptl1 --outputDIR computeProfileLikelihood --makeProfileLikelihood --injectSignal 1 --nToys -1 --rMin -100 --rMax 100 --batchMode --queque 1nh --noGenerateCards --runCombinationOnly --runWWWZCombination  --fakeType fakeLepton
